Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate Interface Reference
jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate Interface Reference
リバーシプレイデリゲート
Public Member Functions
ReversiPlayDelegate (ReversiPlayInterface i)
コンストラクタ
void ViewMsgDlg (String title, String msg)
メッセージダイアログ
void DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
void CurColMsg (String text)
現在の色メッセージ
void CurStsMsg (String text)
現在のステータスメッセージ
void Wait (int time)
ウェイト
Private Attributes
final ReversiPlayInterface impl
デリゲート
Detailed Description
リバーシプレイデリゲート
Definition at line 27 of file ReversiPlayDelegate.java.
Constructor & Destructor Documentation
ReversiPlayDelegate()
jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate.ReversiPlayDelegate (ReversiPlayInterface i)
コンストラクタ
Parameters
[in] ReversiPlayInterface i
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 40 of file ReversiPlayDelegate.java.
Member Function Documentation
CurColMsg()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate.CurColMsg (String text)
現在の色メッセージ
Parameters
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 87 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.CurColMsgLocal().
CurStsMsg()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate.CurStsMsg (String text)
現在のステータスメッセージ
Parameters
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 101 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.CurStsMsgLocal().
DrawSingle()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate.DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 73 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.DrawSingleLocal().
ViewMsgDlg()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate.ViewMsgDlg (String title, String msg)
メッセージダイアログ
Parameters
[in] String title タイトル
[in] String msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 55 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.ViewMsgDlgLocal().
Wait()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayDelegate.Wait (int time)
ウェイト
Parameters
[in] int time ウェイト時間(msec)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 115 of file ReversiPlayDelegate.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.WaitLocal().
The documentation for this interface was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi/model/ReversiPlayDelegate.java