Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi Class Reference
リバーシクラス
Public Member Functions
int [][] getmMasuSts ()
void setmMasuSts (int[][] mMasuSts)
セッター
int [][] getmMasuStsOld ()
void setmMasuStsOld (int[][] mMasuStsOld)
セッター
int [][] getmMasuStsEnaB ()
void setmMasuStsEnaB (int[][] mMasuStsEnaB)
セッター
int [][] getmMasuStsCntB ()
void setmMasuStsCntB (int[][] mMasuStsCntB)
セッター
int [][] getmMasuStsPassB ()
void setmMasuStsPassB (int[][] mMasuStsPassB)
セッター
ReversiAnz [][] getmMasuStsAnzB ()
void setmMasuStsAnzB (ReversiAnz[][] mMasuStsAnzB)
セッター
ReversiPoint [] getmMasuPointB ()
void setmMasuPointB (ReversiPoint[] mMasuPointB)
セッター
int getmMasuPointCntB ()
ゲッター
void setmMasuPointCntB (int mMasuPointCntB)
セッター
int getmMasuBetCntB ()
ゲッター
void setmMasuBetCntB (int mMasuBetCntB)
セッター
int [][] getmMasuStsEnaW ()
void setmMasuStsEnaW (int[][] mMasuStsEnaW)
セッター
int [][] getmMasuStsCntW ()
void setmMasuStsCntW (int[][] mMasuStsCntW)
セッター
int [][] getmMasuStsPassW ()
void setmMasuStsPassW (int[][] mMasuStsPassW)
セッター
ReversiAnz [][] getmMasuStsAnzW ()
void setmMasuStsAnzW (ReversiAnz[][] mMasuStsAnzW)
セッター
ReversiPoint [] getmMasuPointW ()
void setmMasuPointW (ReversiPoint[] mMasuPointW)
セッター
int getmMasuPointCntW ()
ゲッター
void setmMasuPointCntW (int mMasuPointCntW)
セッター
int getmMasuBetCntW ()
ゲッター
void setmMasuBetCntW (int mMasuBetCntW)
セッター
int getmMasuCnt ()
ゲッター
void setmMasuCnt (int mMasuCnt)
セッター
int getmMasuCntMax ()
ゲッター
void setmMasuCntMax (int mMasuCntMax)
セッター
ReversiHistory [] getmMasuHist ()
void setmMasuHist (ReversiHistory[] mMasuHist)
セッター
int getmMasuHistCur ()
ゲッター
void setmMasuHistCur (int mMasuHistCur)
セッター
Reversi (int masuCnt, int masuMax)
コンストラクタ
Reversi ()
コンストラクタ
void reset ()
リセット
void AnalysisReversi (int bPassEna, int wPassEna)
解析を行う
int getMasuSts (int y, int x)
マスステータスを取得
int getMasuStsOld (int y, int x)
以前のマスステータスを取得
int getMasuStsEna (int color, int y, int x)
指定座標に指定色を置けるかチェック
int getMasuStsCnt (int color, int y, int x)
指定座標の獲得コマ数取得
int getColorEna (int color)
指定色が現在置ける場所があるかチェック
int getGameEndSts ()
ゲーム終了かチェック
int setMasuSts (int color, int y, int x)
指定座標にコマを置く
int setMasuStsForcibly (int color, int y, int x)
指定座標にコマを強制的に置く
int setMasuCnt (int cnt)
マスの数変更
ReversiPoint getPoint (int color, int num)
ポイント座標取得
int getPointCnt (int color)
ポイント座標数取得
int getBetCnt (int color)
コマ数取得
int getPassEna (int color, int y, int x)
ReversiHistory getHistory (int num)
履歴取得
int getHistoryCnt ()
履歴数取得
ReversiAnz getPointAnz (int color, int y, int x)
ポイント座標解析取得
int checkEdge (int color, int y, int x)
角の隣に置いても角を取られないマス検索
int getEdgeSideZero (int y, int x)
指定座標が角か取得
int getEdgeSideOne (int y, int x)
指定座標が角の一つ手前か取得
int getEdgeSideTwo (int y, int x)
指定座標が角の二つ手前か取得
int getEdgeSideThree (int y, int x)
指定座標が角の三つ以上手前か取得
Private Member Functions
int makeMasuSts (int color)
各コマの置ける場所等のステータス作成
void revMasuSts (int color, int y, int x)
コマをひっくり返す
int checkPara (int para, int min, int max)
パラメーター範囲チェック
void AnalysisReversiBlack ()
解析を行う(黒)
void AnalysisReversiWhite ()
解析を行う(白)
Private Attributes
int mMasuSts [][]
マスの状態
int mMasuStsOld [][]
以前のマスの状態
int mMasuStsEnaB [][]
黒の置ける場所
int mMasuStsCntB [][]
黒の獲得コマ数
int mMasuStsPassB [][]
黒が相手をパスさせる場所
ReversiAnz mMasuStsAnzB [][]
黒がその場所に置いた場合の解析結果
ReversiPoint mMasuPointB []
黒の置ける場所座標一覧
int mMasuPointCntB
黒の置ける場所座標一覧数
int mMasuBetCntB
黒コマ数
int mMasuStsEnaW [][]
白の置ける場所
int mMasuStsCntW [][]
白の獲得コマ数
int mMasuStsPassW [][]
白が相手をパスさせる場所
ReversiAnz mMasuStsAnzW [][]
白がその場所に置いた場合の解析結果
ReversiPoint mMasuPointW []
白の置ける場所座標一覧
int mMasuPointCntW
白の置ける場所座標一覧数
int mMasuBetCntW
白コマ数
int mMasuCnt
縦横マス数
int mMasuCntMax
縦横マス最大数
ReversiHistory mMasuHist []
履歴
int mMasuHistCur
履歴現在位置
Detailed Description
リバーシクラス
Definition at line 27 of file Reversi.java.
Constructor & Destructor Documentation
Reversi() [1/2]
public jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.Reversi (int masuCnt, int masuMax)
コンストラクタ
Parameters
[in] int masuCnt 縦横マス数
[in] int masuMax 縦横マス最大数
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 560 of file Reversi.java.
Reversi() [2/2]
public jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.Reversi ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 615 of file Reversi.java.
Member Function Documentation
AnalysisReversi()
public void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversi (int bPassEna, int wPassEna)
解析を行う
Parameters
[in] int bPassEna 1=黒パス有効
[in] int wPassEna 1=白パス有効
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1326 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
AnalysisReversiBlack()
private void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack () private
解析を行う(黒)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1044 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversi().
AnalysisReversiWhite()
private void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite () private
解析を行う(白)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1184 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversi().
checkEdge()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.checkEdge (int color, int y, int x)
角の隣に置いても角を取られないマス検索
Parameters
[in] int color 色
[in] int y Y座標
[in] int x X座標
Returns
0 : 取られる それ以外 : 取られない
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1693 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
checkPara()
private int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.checkPara (int para, int min, int max) private
パラメーター範囲チェック
Parameters
[in] int para チェックパラメーター
[in] int min パラメーター最小値
[in] int max パラメーター最大値
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1029 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getBetCnt(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getHistory(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuSts(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuStsCnt(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuStsEna(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuStsOld(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getPoint(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getPointAnz(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuCnt().
getBetCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getBetCnt (int color)
コマ数取得
パス判定
Parameters
[in] int color コマ色
Returns
コマ数取得
Author
Yuta Yoshinaga
Date
2018.04.01
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
パス判定
0 : NOT PASS
1 : PASS
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1596 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayEnd().
getColorEna()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getColorEna (int color)
指定色が現在置ける場所があるかチェック
Parameters
[in] int color コマ色
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1441 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getGameEndSts(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlaySub().
getEdgeSideOne()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getEdgeSideOne (int y, int x)
指定座標が角の一つ手前か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1831 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getEdgeSideThree()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getEdgeSideThree (int y, int x)
指定座標が角の三つ以上手前か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1895 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getEdgeSideTwo()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getEdgeSideTwo (int y, int x)
指定座標が角の二つ手前か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1863 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getEdgeSideZero()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getEdgeSideZero (int y, int x)
指定座標が角か取得
Parameters
[in] int y Y座標
[in] int x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1807 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getGameEndSts()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getGameEndSts ()
ゲーム終了かチェック
Returns
0 : 続行 それ以外 : ゲーム終了
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1463 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlaySub().
getHistory()
public ReversiHistory jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getHistory (int num)
履歴取得
Parameters
[in] int num ポイント
Returns
履歴 null : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1637 of file Reversi.java.
getHistoryCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getHistoryCnt ()
履歴数取得
Returns
履歴数
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1654 of file Reversi.java.
getMasuSts()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuSts (int y, int x)
マスステータスを取得
Parameters
[in] int y 取得するマスのY座標
[in] int x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1366 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.checkEdge(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage().
getMasuStsCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuStsCnt (int color, int y, int x)
指定座標の獲得コマ数取得
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
-1 : 失敗 それ以外 : 獲得コマ数
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1422 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getMasuStsEna()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuStsEna (int color, int y, int x)
指定座標に指定色を置けるかチェック
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
1 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1401 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getColorEna(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuSts().
getMasuStsOld()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getMasuStsOld (int y, int x)
以前のマスステータスを取得
Parameters
[in] int y 取得するマスのY座標
[in] int x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1383 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate().
getmMasuBetCntB()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuBetCntB ()
ゲッター
Returns
int mMasuBetCntB
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 258 of file Reversi.java.
getmMasuBetCntW()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuBetCntW ()
ゲッター
Returns
int mMasuBetCntW
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 433 of file Reversi.java.
getmMasuCnt()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuCnt ()
ゲッター
Returns
int mMasuCnt
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 458 of file Reversi.java.
getmMasuCntMax()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuCntMax ()
ゲッター
Returns
int mMasuCntMax
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 483 of file Reversi.java.
getmMasuHistCur()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuHistCur ()
ゲッター
Returns
int mMasuHistCur
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 533 of file Reversi.java.
getmMasuPointCntB()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuPointCntB ()
ゲッター
Returns
int mMasuPointCntB
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 233 of file Reversi.java.
getmMasuPointCntW()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getmMasuPointCntW ()
ゲッター
Returns
int mMasuPointCntW
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 408 of file Reversi.java.
getPoint()
public ReversiPoint jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getPoint (int color, int num)
ポイント座標取得
Parameters
[in] int color コマ色
[in] int num ポイント
Returns
ポイント座標 null : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1560 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getPointAnz()
public ReversiAnz jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getPointAnz (int color, int y, int x)
ポイント座標解析取得
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
ポイント座標解析 null : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1672 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
getPointCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.getPointCnt (int color)
ポイント座標数取得
Parameters
[in] int color コマ色
Returns
ポイント座標数取得
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1579 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
makeMasuSts()
private int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.makeMasuSts (int color) private
各コマの置ける場所等のステータス作成
Parameters
[in] int color ステータスを作成するコマ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 660 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversi(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.reset(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuSts().
reset()
public void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 628 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.Reversi(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuCnt().
revMasuSts()
private void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.revMasuSts (int color, int y, int x) private
コマをひっくり返す
Parameters
[in] int color ひっくり返す元コマ
[in] int y ひっくり返す元コマのY座標
[in] int x ひっくり返す元コマのX座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 857 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiBlack(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.AnalysisReversiWhite(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuSts().
setMasuCnt()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuCnt (int cnt)
マスの数変更
Parameters
[in] int cnt マスの数
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1536 of file Reversi.java.
setMasuSts()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuSts (int color, int y, int x)
指定座標にコマを置く
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1482 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
setMasuStsForcibly()
public int jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setMasuStsForcibly (int color, int y, int x)
指定座標にコマを強制的に置く
Parameters
[in] int color コマ色
[in] int y マスのY座標
[in] int x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1516 of file Reversi.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.gameEndAnimExec().
setmMasuBetCntB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuBetCntB (int mMasuBetCntB)
セッター
Parameters
[in] int mMasuBetCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 271 of file Reversi.java.
setmMasuBetCntW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuBetCntW (int mMasuBetCntW)
セッター
Parameters
[in] int mMasuBetCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 446 of file Reversi.java.
setmMasuCnt()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuCnt (int mMasuCnt)
セッター
Parameters
[in] int mMasuCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 471 of file Reversi.java.
setmMasuCntMax()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuCntMax (int mMasuCntMax)
セッター
Parameters
[in] int mMasuCntMax
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 496 of file Reversi.java.
setmMasuHist()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuHist (ReversiHistory [] mMasuHist)
セッター
Parameters
[in] ReversiHistory[] mMasuHist
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 521 of file Reversi.java.
setmMasuHistCur()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuHistCur (int mMasuHistCur)
セッター
Parameters
[in] int mMasuHistCur
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 546 of file Reversi.java.
setmMasuPointB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuPointB (ReversiPoint [] mMasuPointB)
セッター
Parameters
[in] ReversiPoint[] mMasuPointB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 221 of file Reversi.java.
setmMasuPointCntB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuPointCntB (int mMasuPointCntB)
セッター
Parameters
[in] int mMasuPointCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 246 of file Reversi.java.
setmMasuPointCntW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuPointCntW (int mMasuPointCntW)
セッター
Parameters
[in] int mMasuPointCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 421 of file Reversi.java.
setmMasuPointW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuPointW (ReversiPoint [] mMasuPointW)
セッター
Parameters
[in] ReversiPoint[] mMasuPointW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 396 of file Reversi.java.
setmMasuSts()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuSts (int mMasuSts[][])
セッター
Parameters
[in] int[][] mMasuSts
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 71 of file Reversi.java.
setmMasuStsAnzB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsAnzB (ReversiAnz mMasuStsAnzB[][])
セッター
Parameters
[in] ReversiAnz[][] mMasuStsAnzB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 196 of file Reversi.java.
setmMasuStsAnzW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsAnzW (ReversiAnz mMasuStsAnzW[][])
セッター
Parameters
[in] ReversiAnz[][] mMasuStsAnzW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 371 of file Reversi.java.
setmMasuStsCntB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsCntB (int mMasuStsCntB[][])
セッター
Parameters
[in] int[][] mMasuStsCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 146 of file Reversi.java.
setmMasuStsCntW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsCntW (int mMasuStsCntW[][])
セッター
Parameters
[in] int[][] mMasuStsCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 321 of file Reversi.java.
setmMasuStsEnaB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsEnaB (int mMasuStsEnaB[][])
セッター
Parameters
[in] int[][] mMasuStsEnaB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 121 of file Reversi.java.
setmMasuStsEnaW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsEnaW (int mMasuStsEnaW[][])
セッター
Parameters
[in] int[][] mMasuStsEnaW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 296 of file Reversi.java.
setmMasuStsOld()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsOld (int mMasuStsOld[][])
セッター
Parameters
[in] int[][] mMasuStsOld
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 96 of file Reversi.java.
setmMasuStsPassB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsPassB (int mMasuStsPassB[][])
セッター
Parameters
[in] int[][] mMasuStsPassB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 171 of file Reversi.java.
setmMasuStsPassW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.Reversi.setmMasuStsPassW (int mMasuStsPassW[][])
セッター
Parameters
[in] int[][] mMasuStsPassW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 346 of file Reversi.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi/model/Reversi.java