Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi.model.CallbacksJson Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi.model.CallbacksJson Class Reference
コールバックJSONクラス
Public Member Functions
ArrayList< FuncsJson > getFuncs ()
ゲッター
void setFuncs (ArrayList< FuncsJson > funcs)
セッター
CallbacksJson ()
コンストラクタ
Private Attributes
ArrayList< FuncsJson > funcs
Detailed Description
コールバックJSONクラス
Definition at line 28 of file CallbacksJson.java.
Constructor & Destructor Documentation
CallbacksJson()
public jp.gr.java_conf.yuta_yoshinaga.reversi.model.CallbacksJson.CallbacksJson ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 65 of file CallbacksJson.java.
Member Function Documentation
getFuncs()
ArrayList< FuncsJson > jp.gr.java_conf.yuta_yoshinaga.reversi.model.CallbacksJson.getFuncs ()
ゲッター
Returns
ArrayList<FuncsJson> funcs
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 40 of file CallbacksJson.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.CurColMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.CurStsMsg(), jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.DrawSingle(), jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.ViewMsgDlg(), and jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.Wait().
setFuncs()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.CallbacksJson.setFuncs (ArrayList< FuncsJson > funcs)
セッター
Parameters
[in] ArrayList<FuncsJson> funcs
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 53 of file CallbacksJson.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi/model/CallbacksJson.java