Javaリバーシプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
Reversi getmReversi ()
ゲッター
void setmReversi (Reversi mReversi)
セッター
ReversiSetting getmSetting ()
ゲッター
void setmSetting (ReversiSetting mSetting)
セッター
int getmCurColor ()
ゲッター
void setmCurColor (int mCurColor)
セッター
ReversiPoint [] getmCpu ()
void setmCpu (ReversiPoint[] mCpu)
セッター
ReversiPoint [] getmEdge ()
void setmEdge (ReversiPoint[] mEdge)
セッター
int getmPassEnaB ()
ゲッター
void setmPassEnaB (int mPassEnaB)
セッター
int getmPassEnaW ()
ゲッター
void setmPassEnaW (int mPassEnaW)
セッター
int getmGameEndSts ()
ゲッター
void setmGameEndSts (int mGameEndSts)
セッター
int getmPlayLock ()
ゲッター
void setmPlayLock (int mPlayLock)
セッター
Random getR ()
ゲッター
void setR (Random r)
セッター
ReversiPlayDelegate getmDelegate ()
ゲッター
void setmDelegate (ReversiPlayDelegate mDelegate)
セッター
CallbacksJson getmCallbacks ()
ゲッター
void setmCallbacks (CallbacksJson mCallbacks)
セッター
ReversiPlay ()
コンストラクタ
void reversiPlay (int y, int x)
リバーシプレイ
void reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
void reversiPlayEnd ()
リバーシプレイ終了
void reversiPlayPass (int color)
リバーシプレイパス
int reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
void drawUpdate (int assist)
マス描画更新
void drawUpdateForcibly (int assist)
マス描画強制更新
void reset ()
リセット処理
int gameEndAnimExec ()
ゲーム終了アニメーション
void sendDrawMsg (int y, int x)
描画メッセージ送信
void sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Private Member Functions
void execMessage (int what, Object obj)
メッセージ
void ViewMsgDlgLocal (String title, String msg)
メッセージダイアログ
void DrawSingleLocal (int y, int x, int sts, int bk, String text)
1マス描画
void CurColMsgLocal (String text)
現在の色メッセージ
void CurStsMsgLocal (String text)
現在のステータスメッセージ
void WaitLocal (int time)
ウェイト
Private Attributes
Reversi mReversi
リバーシクラス
ReversiSetting mSetting
リバーシ設定クラス
int mCurColor
現在の色
ReversiPoint [] mCpu
CPU用ワーク
ReversiPoint [] mEdge
CPU用角マスワーク
int mPassEnaB
黒のパス有効フラグ
int mPassEnaW
白のパス有効フラグ
int mGameEndSts
ゲーム終了ステータス
int mPlayLock
プレイロック
Random r
乱数
ReversiPlayDelegate mDelegate
デリゲート
CallbacksJson mCallbacks
コールバック
Detailed Description
リバーシプレイクラス
Definition at line 28 of file ReversiPlay.java.
Constructor & Destructor Documentation
ReversiPlay()
jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.ReversiPlay ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 351 of file ReversiPlay.java.
Member Function Documentation
CurColMsgLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.CurColMsgLocal (String text) private
現在の色メッセージ
Parameters
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1176 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage().
CurStsMsgLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.CurStsMsgLocal (String text) private
現在のステータスメッセージ
Parameters
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1190 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage().
DrawSingleLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.DrawSingleLocal (int y, int x, int sts, int bk, String text) private
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] String text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1162 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage().
drawUpdate()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate (int assist)
マス描画更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 834 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
drawUpdateForcibly()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdateForcibly (int assist)
マス描画強制更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 867 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset().
execMessage()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.execMessage (int what, Object obj) private
メッセージ
Parameters
[in] int what
[in] Object obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1049 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdateForcibly(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayEnd(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.sendDrawInfoMsg(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.sendDrawMsg().
gameEndAnimExec()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.gameEndAnimExec ()
ゲーム終了アニメーション
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 942 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayEnd().
getmCallbacks()
CallbacksJson jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmCallbacks ()
ゲッター
Returns
CallbacksJson mCallbacks
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 326 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.doPost().
getmCurColor()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmCurColor ()
ゲッター
Returns
int mCurColor
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 101 of file ReversiPlay.java.
getmDelegate()
ReversiPlayDelegate jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmDelegate ()
ゲッター
Returns
ReversiPlayDelegate mDelegate
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 301 of file ReversiPlay.java.
getmGameEndSts()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmGameEndSts ()
ゲッター
Returns
int mGameEndSts
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 226 of file ReversiPlay.java.
getmPassEnaB()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmPassEnaB ()
ゲッター
Returns
int mPassEnaB
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 176 of file ReversiPlay.java.
getmPassEnaW()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmPassEnaW ()
ゲッター
Returns
int mPassEnaW
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 201 of file ReversiPlay.java.
getmPlayLock()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmPlayLock ()
ゲッター
Returns
int mPlayLock
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 251 of file ReversiPlay.java.
getmReversi()
Reversi jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmReversi ()
ゲッター
Returns
Reversi mReversi
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 51 of file ReversiPlay.java.
getmSetting()
ReversiSetting jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getmSetting ()
ゲッター
Returns
ReversiSetting mSetting
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 76 of file ReversiPlay.java.
getR()
Random jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.getR ()
ゲッター
Returns
Random r
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 276 of file ReversiPlay.java.
reset()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reset ()
リセット処理
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 892 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.doPost().
reversiPlay()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay (int y, int x)
リバーシプレイ
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 381 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.doPost().
reversiPlayCpu()
int jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
Parameters
[in] int color CPU色
[in] int cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 575 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlaySub().
reversiPlayEnd()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayEnd ()
リバーシプレイ終了
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 505 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlaySub().
reversiPlayPass()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayPass (int color)
リバーシプレイパス
Parameters
[in] int color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 553 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlaySub().
reversiPlaySub()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
Parameters
[in] int cpuEna
[in] int tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 475 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay().
sendDrawInfoMsg()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1030 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate().
sendDrawMsg()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.sendDrawMsg (int y, int x)
描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1011 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayCpu().
setmCallbacks()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmCallbacks (CallbacksJson mCallbacks)
セッター
Parameters
[in] CallbacksJson mCallbacks
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 339 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.doPost().
setmCpu()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmCpu (ReversiPoint [] mCpu)
セッター
Parameters
[in] ReversiPoint[] mCpu
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 139 of file ReversiPlay.java.
setmCurColor()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmCurColor (int mCurColor)
セッター
Parameters
[in] int mCurColor
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 114 of file ReversiPlay.java.
setmDelegate()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmDelegate (ReversiPlayDelegate mDelegate)
セッター
Parameters
[in] ReversiPlayDelegate mDelegate
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 314 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.doPost().
setmEdge()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmEdge (ReversiPoint [] mEdge)
セッター
Parameters
[in] ReversiPoint[] mEdge
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 164 of file ReversiPlay.java.
setmGameEndSts()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmGameEndSts (int mGameEndSts)
セッター
Parameters
[in] int mGameEndSts
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 239 of file ReversiPlay.java.
setmPassEnaB()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmPassEnaB (int mPassEnaB)
セッター
Parameters
[in] int mPassEnaB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 189 of file ReversiPlay.java.
setmPassEnaW()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmPassEnaW (int mPassEnaW)
セッター
Parameters
[in] int mPassEnaW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 214 of file ReversiPlay.java.
setmPlayLock()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmPlayLock (int mPlayLock)
セッター
Parameters
[in] int mPlayLock
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 264 of file ReversiPlay.java.
setmReversi()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmReversi (Reversi mReversi)
セッター
Parameters
[in] Reversi mReversi
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 64 of file ReversiPlay.java.
setmSetting()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setmSetting (ReversiSetting mSetting)
セッター
Parameters
[in] ReversiSetting mSetting
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 89 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.FrontController.doPost().
setR()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.setR (Random r)
セッター
Parameters
[in] Random r
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 289 of file ReversiPlay.java.
ViewMsgDlgLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.ViewMsgDlgLocal (String title, String msg) private
メッセージダイアログ
Parameters
[in] String title タイトル
[in] String msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1144 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayEnd(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayPass().
WaitLocal()
void jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.WaitLocal (int time) private
ウェイト
Parameters
[in] int time ウェイト時間(msec)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.04.01
Definition at line 1204 of file ReversiPlay.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.drawUpdate(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.gameEndAnimExec(), jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlay.reversiPlayEnd().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/reversi/model/ReversiPlay.java